# ML wrapper config (does not change current task2simple flow)

# Path to existing Task2 simple config
# (used by project2.task2simple.KMeansMain)
task2.config.path=/home/ds503/project2_task2_config.properties

# Scaling
scaler.use=true
scaler.method=zscore
scaler.stats.path=/project2/task2ml/scaler/stats

# Fit (train)
train.input.raw=/project2/task2/input/points_4d.csv
train.input.scaled=/project2/task2ml/scaled/train
fit.mode=OPT_CENTERS
model.base=/project2/task2ml/model
model.centers.path=
model.sse.path=/project2/task2ml/model/metrics_sse

# Predict
predict.input.raw=/project2/task2/input/points_4d.csv
predict.input.scaled=/project2/task2ml/scaled/predict
predict.output.base=/project2/task2ml/predict
